from pydantic import BaseModel, Field
from typing import List, Optional


class PropertyListing(BaseModel):
    name_en: Optional[str] = Field(..., description="Property name in English")
    price: Optional[int] = Field(..., description="Rental price per month in Thai Baht")
    # latitude: float = Field(..., description="Latitude coordinate of the property")
    # longitude: float = Field(..., description="Longitude coordinate of the property")
    routed_distance: Optional[str] = Field(None, description="Distance to key locations (if available)")
    routed_time: Optional[str] = Field(None, description="Time to key locations (if available)")
    nearest_stations: Optional[str] = Field(None, description="Nearest public transport stations")
    # agent_name: str = Field(..., description="Name of the contact person/agent")
    # isAgency: bool = Field(..., description="Boolean indicating if the contact is an agency")
    # cctv: bool = Field(..., description="Boolean indicating if the property has CCTV")
    # lift: bool = Field(..., description="Boolean indicating if the property has a lift")
    # park: bool = Field(..., description="Boolean indicating if the property has a park")
    pool: Optional[bool] = Field(..., description="Boolean indicating if the property has a pool")
    # shop: bool = Field(..., description="Boolean indicating if the property has a shop")
    wifi: Optional[bool] = Field(..., description="Boolean indicating if the property has Wi-Fi")
    sauna: Optional[bool] = Field(..., description="Boolean indicating if the property has a sauna")
    # steam: bool = Field(..., description="Boolean indicating if the property has a steam room")
    fitness: Optional[bool] = Field(..., description="Boolean indicating if the property has a fitness center")
    jacuzzi: Optional[bool] = Field(..., description="Boolean indicating if the property has a jacuzzi")
    keycard: Optional[bool] = Field(..., description="Boolean indicating if the property has keycard access")
    laundry: Optional[bool] = Field(..., description="Boolean indicating if the property has laundry facilities")
    # library: bool = Field(..., description="Boolean indicating if the property has a library")
    # massage: bool = Field(..., description="Boolean indicating if the property has massage facilities")
    parking: Optional[bool] = Field(..., description="Boolean indicating if the property has parking")
    shuttle: Optional[bool] = Field(..., description="Boolean indicating if the property has a shuttle service")
    allowPet: Optional[bool] = Field(..., description="Boolean indicating if pets are allowed")
    security: Optional[bool] = Field(..., description="Boolean indicating if the property has security services")
    # evCharger: bool = Field(..., description="Boolean indicating if the property has an EV charger")
    # playground: bool = Field(..., description="Boolean indicating if the property has a playground")
    restaurant: Optional[bool] = Field(..., description="Boolean indicating if the property has a restaurant")
    # fingerprint: bool = Field(..., description="Boolean indicating if the property has fingerprint access")
    # accessControl: bool = Field(..., description="Boolean indicating if the property has access control")
    # bicycleParking: bool = Field(..., description="Boolean indicating if the property has bicycle parking")
    # motorcycleParking: bool = Field(..., description="Boolean indicating if the property has motorcycle parking")